# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'intro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for intro

  target 'intro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'introTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'